### PR TITLE
add a way to override the usage of window

### PR DESCRIPTION
**Pull request by aitboudad**
This will allow supports angular universal through angular service overrides

### CODE REVIEW

**Comment by ronzeidman** [comment]
I didn't try universal yet. can you give a snippet of how to override it after your change?

**Comment by aitboudad** [comment]
```ts
import { ConfigService } from 'ng2-ui-auth';

@Injectable()
export class UiAuthConfigBackendService extends ConfigService {
    getHttpHost(path = '') {
        return BASE_URL + path;
    }

    isCordovaApp() {
        return false;
    }
}

@NgModule({
    imports: [
        ...
        UniversalModule,
    ],
    providers: [
        ...
        { provide: ConfigService, useClass: UiAuthConfigBackendService },
    ],
})
export class AppNodeModule {}
```

**Comment by ronzeidman** [comment]
Thanks, great.
I'll merge it and it will be included in the next release

**Comment by phl3x0r** [comment]
Hello. As I too had the problem of running this with Universal, I tried out this solution, but this gives me the folowing error:

> Exception: Call to Node module failed with error: Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to object
> TypeError: Cannot convert undefined or null to object
> at UiAuthConfigBackendService.ConfigService (C:\Users\wisps\Source\Repos\job-auction-app\JAWS\Jawper.com\node_modules\ng2-ui-auth\commonjs\config.service.js:199:16)

Line 199 is: 
`Object.keys(config).forEach(function (key) {`

How do I resolve this?

**Comment by aitboudad** [comment]
@phl3x0r try with:

```ts
import { CustomConfig } from 'ng2-ui-auth';

@Injectable()
export class UiAuthConfigBackendService extends ConfigService {
    constructor(config?: CustomConfig) {
        super(config);
    }
    ...
}
```

**Comment by phl3x0r** [comment]
That worked, thanks!

**Pull request merged**
