### PR TITLE
Exception when reading 'exp from undefined' for 'getExpirationDate'

### PR DESCRIPTION
**Pull request by barinovos**
Wrong boolean operator triggers unhandled exception when reading 'exp from undefined'. Happens when call 'getExpirationDate' with non-base64 token (SharedService). Fixed.

### CODE REVIEW

**Comment by ronzeidman** [comment]
can you give an example value of `this.getPayload()` that your fix handles correctly and the original code does not?

**Comment by barinovos** [comment]
Our access token example: 
f61b6b86-2e1b-4d04-bba7-3303e6984889

But.. I also found, that this not fully solve an issue, that we have.
Currently, we are using our own Http wrapper (like yours JwtHttp) and also store access token and expiration date in local storage with our own keys.
But you strongly use JwtHttp to make request with included Authorization token even for Auth endpoint (we use server-side auth with Google), but our server blocks response with Google auth data to get token because of already presented token in the request.
So.. I would also be glad to make another pull request with changes to use simple Http factory for auth POST request instead of JwtHttp one..

**Comment by ronzeidman** [comment]
With the latest version (master, not the npm one) you can replace the JwtHttp with the standard Http by using - `forRootWithCustomHttp` function in the module: https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/ng2-ui-auth.module.ts#L32
The reason why I'm using JwtHttp is so you could configure in the configuration the "default headers" to send.

On anther note, it seems like you are abusing this library a bit. It seems you use "session cookie" (even if you store the "cookie" in the localstorage instead of as an actual cookie) instead of JWT token to talk with your server. Consider creating a JWT token instead and this library will make much more sense:
https://ponyfoo.com/articles/json-web-tokens-vs-session-cookies

If you want to remain with a session cookie, please create a fork (if you haven't already) and when you manage to modify it enough to make it work with session cookie out of the box I'll look at it and see if I can incorporate your changes to make it configurable (`authType: 'JWT' | 'session' `)

**Comment by barinovos** [comment]
You understood wrong, we are still using token, but not in XXX.YYY.ZZZ format.

Ok, `forRootWithCustomHttp` will help us, but you still didn't publish `6.0.0` in npm, last available is `5.0.0` (without this change)

**Comment by ronzeidman** [comment]
It just seemed that your access token looks just like a GUID, and since it doesn't look long enough to contain information about the userId + expiration +- scope + signature it seems like what you do is store it as a temporary id (if it's not temporary it's a security issue) for a specific session and therefore need a "session store" in the server-side. That is exactly what "token" authentication meant to avoid, your authentication looks more like how a "session cookie" works which is fine, but currently not in the scope of this library (if the changes are not that big maybe it can be, but not currently).

I know, this was a new addition and I'm still verifying that everything works, I'll probably publish it to npm in the next couple of days if everything goes well.

I've tried doing something like this: `{provide: JwtHttp, useClass: MyHttp, deps: [Http, SharedService, ConfigService]}` and it worked fine. Notice that in version 6 the JwtHttp does not inherit from Http but use it in it's constructor so maybe you'll have to do something similar in your `OurHttp`. If it doesn't work can you provide write your `OurHttp` or something similar that causes this issue so I could find a way to fix it? I won't publish the package on npm until it's fixed.

Thanks

**Comment by barinovos** [comment]
From our auth endpoint we get a JSON object with the fields `{access_token: GUID, expires_in: ms, refresh_token: GUID, permissions: whatever}`. And our `OurHttp` (let's agree on this alias) works exactly like `JwtHttp` - also use `Http` as dependency (no inheritance), wrap all methods, set headers (and also `Authorization`) and we also use kinda of `AuthService`, which set token and expiration data in localStorage, reads from it, clean on logout, validate the expiration and so on..
So only one functional, that we really need from current library - to open popup on pressing 'google' button, allow user to choose account or enter credentials, read the oauth data from it, set additional Request headers for our backend and send a request to provided URL with provided headers and data from Google.. all other stuff we already handles by own services..

We can push our BE guys to work with pure JWT format, but they told, that it requires too much effort for them...

Thank you for your replies, by the way!

**Comment by barinovos** [comment]
Ok, using `{provide: JwtHttp, useFactory: (http:Http) => ..., deps: [Http]}` works.. but looks ugly, I've created a special factory just to handle only `post` method of Http, set up proper headers and that's all..

**Comment by ronzeidman** [comment]
No problem, just never seen anyone working like that. Also since there's no signature I'm guessing the payload is not sent back to the server so the server would still have to query the permissions and the "token" would still have to be saved in a session store.
I'm not judging or anything, just curious.
I'll close this pull request. 
Maybe I could make this library more modular. You could probably use the Oauth2Service or the popup service directly but if you can just replace the HTTP service and it works for you it's probably not worth it.
Any suggestions or improvements are welcome.
Happy holidays!

**Comment by barinovos** [comment]
No, we are not using any 'session store', we just have a token, which we keep in localStorage and add it to each API request. Nothing weird in it )

> Maybe I could make this library more modular

this is a good idea, because right now the functional of your services is too strong bounded to each other, which makes it not so flexible for different use cases..
But anyway thanks! )
Always ready to contribute if needed...

**Comment by ronzeidman** [comment]
You're right, I'll probably decouple the services in the next version.
Thanks

**Pull request closed without merging**
