### PR TITLE
update packages + fixed support for TypeScript 2.4

### PR DESCRIPTION
**Pull request by aitboudad**
+ removed build files (`commonjs` and `bundle`) from git as it's only useful in npm package.

### CODE REVIEW

**Comment by ronzeidman** [comment]
I've been afraid to update this libraries deps so I won't break compatibility with older angular2 versions. Where and what was the issue with typescript 2.4? I have a project using it (and I recently updated to typescript 2.4 although disabled lib check since rxjs had an issue with "lift" and I think angular itself had another...) maybe it's better to just fix the typescript 2.4 issue and keep the deps old as long as it can support all the old versions along with the latest ones?

**Comment by aitboudad** [comment]
`rxjs` has fixed the `lift` issue in `5.4.2` also updating packages doesn't means we drop the support of angular2 (to be verified).

**Comment by ronzeidman** [comment]
I'm not 100% sure that angular 2.x accepts AOT complied metadata of 4.x so I'll have to verify it before merging this pull request. 
Anyway, thanks for the pull request! much appreciated.

**Comment by aitboudad** [comment]
Ok as you like, let me know if you want keep the old deps ;).

For typescript 2.4 the solved issue is in [oauth.service](https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/oauth.service.ts#L24)
```ts
Type 'Oauth1Service | Oauth2Service' is not assignable to type '{ open(options?: IOauth1Options, userData?: any): Observable<Response>; }'.
```

**Comment by ronzeidman** [comment]
Maybe I'll just add a notice and bump the major version. I think most people who care about using the up-to-date version also updated the angular version itself.

**Pull request merged**
