### PR TITLE
Throw error when user closes the popup window

### PR DESCRIPTION
**Pull request by royipressburger**
I think that when we prompt a user with the popup window, we should throw error in case the user closes the window without entering credentials.

### CODE REVIEW

**Comment by ronzeidman** [comment]
This will also make the "takeWhile" redundant.
I'll look more into it this weekend.

**Comment by royipressburger** [comment]
Yea i saw that after i commited to pull request.
There is also a similar in the eventListening method that i had no idea who use that :/

**Comment by royipressburger** [comment]
Actually I think I missed something. when testing this I saw that there are two ways to return from that modal: One by clicking the back button and the other by a close icon inside the modal (At least on an android device.) The error is not invoked when using the close icon

**Comment by ronzeidman** [comment]
Can you try 6.1.0, I've thrown a `new Error('Authentication Canceled');` when the window closes.
all you need to do when authenticating is 
```ts
.subscribe(
    next => <do something>,
    error => <do something and stop spinner>,
    (/* complete */) => <stop spinner>
)
```

**Pull request closed without merging**
